# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 20:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160801_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='description',
            new_name='name',
        ),
    ]
