# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20161202_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='document/'),
        ),
    ]
