# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20161202_1429'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='files',
        ),
    ]
