# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_math'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
