# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20161202_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='courses',
            field=models.CharField(choices=[('M', 'Math'), ('A', 'Art'), ('S', 'Science'), ('H', 'History'), ('E', 'English')], max_length=25),
        ),
    ]
