# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-02 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20161202_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='courses',
            field=models.CharField(choices=[('Math', 'Math'), ('Art', 'Art'), ('Science', 'Science'), ('History', 'History'), ('English', 'English')], max_length=1),
        ),
    ]
