# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-03 01:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20161202_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Math',
        ),
    ]
